language: python
python:
- '2.6'
before_script:
- sudo apt-get -y update && sudo apt-get -y install devscripts build-essential equivs
- sudo mk-build-deps -i
- gpg --import $PPA_KEY_FILE
script: yes | debuild -S -I -k$PPA_KEY_ID -p"gpg --passphrase $PPA_KEY_PASSWORD"
after_success: debrelease -S --dput ppa:$PPA_NAME
env:
  global:
  - secure: iIcAJFLkhwGUZW0Z5sHDH2HU1l57sj2YjfAQnD+RLh4+H8lt/ZJ8FhGsjELcOR9dvHHOiPIjB80R0McmCeRW720+ja5imHK/V2y9H0OKxLI9LtG8hGkVTvdIfrNH58dexUA+kn1RnSmLmsLyzNyY9T4q4oU1U6eUBd31SIKkRsA=
  - PPA_KEY_ID=467C4B6F PPA_KEY_FILE=.travis/python-flock-ppa.gpg PPA_NAME=syndicut/python-flock